export type Lang = "zh" | "en";
export type LocalizedText = { zh: string; en: string };
export type RiskLevel = "low" | "medium" | "high";

export type TutorialSource = {
  id: string;
  title: LocalizedText;
  url: string;
  domain: string;
  tier: "S" | "A";
  accessedAt: string;
  citedSteps: string[];
};

export type TutorialStep = {
  id: string;
  title: LocalizedText;
  body: LocalizedText;
  caution?: LocalizedText;
  sourceIds: string[];
  image?: { src: string; alt: LocalizedText; caption: LocalizedText; sourceId: string };
};

export type Tutorial = {
  id: string;
  slug: string;
  version: string;
  lastVerified: string;
  title: LocalizedText;
  summary: LocalizedText;
  goal: LocalizedText;
  task: string;
  platforms: string[];
  devices: string[];
  regions: string[];
  coins: string[];
  networks: string[];
  risk: RiskLevel;
  duration: LocalizedText;
  feeType: LocalizedText;
  scope: LocalizedText;
  prerequisites: LocalizedText[];
  steps: TutorialStep[];
  checklist: LocalizedText[];
  success: LocalizedText[];
  txid: LocalizedText;
  faq: { q: LocalizedText; a: LocalizedText }[];
  sources: TutorialSource[];
  changeLog: { date: string; note: LocalizedText }[];
};

export const l = (zh: string, en: string): LocalizedText => ({ zh, en });
const verified = "2026-08-05";

const sources = {
  metamaskInstall: { id: "metamask-install", title: l("MetaMask：开始使用与安装", "MetaMask: Get started and install"), url: "https://support.metamask.io/start/getting-started-with-metamask", domain: "support.metamask.io", tier: "S" as const, accessedAt: verified, citedSteps: ["2", "3"] },
  metamaskReal: { id: "metamask-real", title: l("MetaMask：识别真实 MetaMask", "MetaMask: Recognize the real MetaMask"), url: "https://support.metamask.io/stay-safe/safety-in-web3/how-do-i-recognize-the-real-metamask-/", domain: "support.metamask.io", tier: "S" as const, accessedAt: verified, citedSteps: ["1", "2"] },
  metamaskSend: { id: "metamask-send", title: l("MetaMask：发送代币", "MetaMask: Send tokens"), url: "https://support.metamask.io/manage-crypto/move-crypto/send/how-to-send-tokens-from-your-metamask-wallet", domain: "support.metamask.io", tier: "S" as const, accessedAt: verified, citedSteps: ["2", "3", "4"] },
  metamaskReceive: { id: "metamask-receive", title: l("MetaMask：从 Binance 收款与排查", "MetaMask: Receive from Binance and troubleshoot"), url: "https://support.metamask.io/manage-crypto/move-crypto/transfer/receiving-funds-from-binance", domain: "support.metamask.io", tier: "S" as const, accessedAt: verified, citedSteps: ["2", "3"] },
  ledgerPhrase: { id: "ledger-phrase", title: l("Ledger：恢复短语基础", "Ledger: Secret recovery phrase basics"), url: "https://www.ledger.com/academy/basic-basics/2-how-to-own-crypto/whats-a-secret-recovery-phrase", domain: "ledger.com", tier: "S" as const, accessedAt: verified, citedSteps: ["1", "2", "3"] },
  ledgerBuy: { id: "ledger-buy", title: l("Ledger：安全购买设备", "Ledger: Securely buy a device"), url: "https://www.ledger.com/academy/topics/ledgersolutions/best-practices-to-securely-buy-ledger-signer", domain: "ledger.com", tier: "S" as const, accessedAt: verified, citedSteps: ["1", "2"] },
  trezorSuite: { id: "trezor-suite", title: l("Trezor：下载并校验 Trezor Suite", "Trezor: Download and verify Trezor Suite"), url: "https://trezor.io/guides/trezor-suite/download-verify-trezor-suite", domain: "trezor.io", tier: "S" as const, accessedAt: verified, citedSteps: ["2", "3"] },
  trezorAuth: { id: "trezor-auth", title: l("Trezor：设备真实性检查", "Trezor: Device authentication check"), url: "https://trezor.io/learn/security-privacy/how-trezor-keeps-you-safe/trezor-safe-device-authentication-check", domain: "trezor.io", tier: "S" as const, accessedAt: verified, citedSteps: ["2", "3"] },
  okxWithdraw: { id: "okx-withdraw", title: l("欧易：网页端提币流程", "OKX: Web withdrawal flow"), url: "https://www.okx.com/en-us/help/how-do-i-make-a-withdrawal-web", domain: "okx.com", tier: "S" as const, accessedAt: verified, citedSteps: ["1", "2", "3", "4"] },
  okxDeposit: { id: "okx-deposit", title: l("欧易：查找充币地址和 Memo/Tag", "OKX: Find deposit address and Memo/Tag"), url: "https://www.okx.com/zh-hans/help/how-do-i-find-my-deposit-address-and-tag-memos", domain: "okx.com", tier: "S" as const, accessedAt: verified, citedSteps: ["1", "2", "3"] },
  coinbaseMemo: { id: "coinbase-memo", title: l("Coinbase：Memo/Tag 与小额测试", "Coinbase: Memo/Tag and test transfers"), url: "https://help.coinbase.com/en/pro/trading-and-funding/depositing-or-withdrawing/destination-tag-memo-faq", domain: "help.coinbase.com", tier: "S" as const, accessedAt: verified, citedSteps: ["2", "3", "4"] },
  ftcScams: { id: "ftc-scams", title: l("美国联邦贸易委员会：加密货币诈骗", "FTC: Cryptocurrency scams"), url: "https://consumer.ftc.gov/articles/what-know-about-cryptocurrency-scams", domain: "consumer.ftc.gov", tier: "S" as const, accessedAt: verified, citedSteps: ["1", "2", "3", "4"] },
};

const transferChecklist = [
  l("币种：发送端与接收端显示的是同一种资产", "Asset: sender and receiver show the same asset"),
  l("网络：发送网络与接收网络完全一致", "Network: sending and receiving networks match exactly"),
  l("地址：核对首尾字符，不依赖剪贴板一次复制", "Address: compare first and last characters; do not trust one paste"),
  l("Memo/Tag：接收端要求时必须同时填写", "Memo/Tag: include it whenever the receiver requires it"),
  l("金额与费用：保留足够 Gas，并确认净到账金额", "Amount and fees: keep enough gas and verify the net amount"),
];

const basicFaq = [
  { q: l("页面与教程不一致怎么办？", "What if the page differs from this guide?"), a: l("暂停操作，核对目标域名、平台版本和最后核验日期；不要凭相似按钮猜测。可使用页底反馈按钮联系我们。", "Stop, verify the domain, platform version, and review date. Do not guess from similar buttons; use the feedback button below.") },
  { q: l("可以把助记词发给客服核验吗？", "Can I send a recovery phrase to support for verification?"), a: l("不可以。任何客服、群聊、表单或远程协助都不需要你的助记词或私钥。", "No. Support, chats, forms, and remote-assistance tools never need your recovery phrase or private key.") },
];

const img = (file: string, zh: string, en: string, sourceId: string) => ({ src: `/tutorial-images/${file}`, alt: l(zh, en), caption: l(`${zh}。原创标注示意图，依据所列官方资料整理，不复刻账户界面。`, `${en}. Original annotated diagram based on the listed official source; no account UI is reproduced.`), sourceId });
const step = (id: string, zhTitle: string, enTitle: string, zhBody: string, enBody: string, sourceIds: string[], image?: ReturnType<typeof img>, caution?: LocalizedText): TutorialStep => ({ id, title: l(zhTitle, enTitle), body: l(zhBody, enBody), sourceIds, image, caution });

type Seed = Omit<Tutorial, "version" | "lastVerified" | "faq" | "changeLog"> & { faq?: Tutorial["faq"] };
const tutorial = (seed: Seed): Tutorial => ({ ...seed, version: "1.0", lastVerified: verified, faq: seed.faq ?? basicFaq, changeLog: [{ date: verified, note: l("首版发布前本地验收稿。", "Initial local acceptance draft before publication.") }] });

export const tutorials: Tutorial[] = [
  tutorial({
    id: "P0-01", slug: "custody-exchange-software-hardware-wallet", title: l("先分清：交易所、软件钱包、硬件钱包", "First: exchange, software wallet, or hardware wallet?"), summary: l("先判断谁控制资产，再决定该用哪类工具。", "Decide who controls the assets before choosing a tool."), goal: l("理解托管与自托管的责任边界，并选出适合当前任务的载体。", "Understand custody responsibilities and choose the right tool for the task."), task: "basics", platforms: ["通用 / General"], devices: ["网页 / Web", "手机 / Mobile", "硬件 / Hardware"], regions: ["全球 / Global"], coins: ["通用 / Any"], networks: ["通用 / Any"], risk: "medium", duration: l("8–12 分钟", "8–12 min"), feeType: l("无", "None"), scope: l("适合尚未转账、正在选择存放方式的新手。", "For beginners choosing how to hold assets before making a transfer."), prerequisites: [l("不需要注册或连接钱包", "No registration or wallet connection needed"), l("列出自己最担心的风险：忘记密码、设备丢失或平台限制", "List your main concern: forgotten password, lost device, or platform restrictions")],
    steps: [
      step("1", "识别交易所账户", "Identify an exchange account", "交易所代表你保管账户内资产，找回流程通常依赖登录、身份验证和平台规则。适合频繁使用，但你不直接持有链上私钥。", "An exchange custodies assets in your account. Recovery usually depends on login, identity checks, and platform rules; you do not hold the on-chain key.", ["ftc-scams"]),
      step("2", "识别软件钱包", "Identify a software wallet", "软件钱包让你直接控制助记词或私钥。App 或扩展只是操作界面，恢复能力来自备份，而不是账号客服。", "A software wallet gives you direct control through a recovery phrase or private key. The app is an interface; recovery depends on your backup, not support.", ["metamask-install"], img("metamask-install.webp", "MetaMask 官方入门页面", "MetaMask official getting-started page", "metamask-install")),
      step("3", "识别硬件钱包", "Identify a hardware wallet", "硬件钱包把签名密钥隔离在专用设备中。你仍需保管恢复短语，并在设备屏幕核对地址和操作。", "A hardware wallet isolates signing keys in a dedicated device. You still protect the recovery phrase and verify actions on the device screen.", ["ledger-phrase"]),
      step("4", "按任务选择", "Choose by task", "短期平台操作可使用交易所；日常链上交互使用已核验的软件钱包；长期或较大额自托管可考虑正规来源的硬件钱包。不要把任何一种工具当成绝对安全。", "Use an exchange for short-term platform tasks, a verified software wallet for routine on-chain activity, and a genuine hardware wallet for longer-term or larger self-custody. None is absolutely safe.", ["ledger-buy"]),
    ], checklist: [l("我知道资产由平台还是由我自己控制", "I know whether the platform or I control the assets"), l("我知道恢复凭证由谁保管", "I know who holds the recovery credential"), l("我选择的工具与使用频率和风险承受能力相符", "The tool matches my usage and risk tolerance")], success: [l("能用一句话说明托管与自托管差别", "You can explain custody vs. self-custody in one sentence"), l("已决定下一步阅读软件钱包、交易所或硬件钱包教程", "You have chosen the next software wallet, exchange, or hardware wallet guide")], txid: l("本篇不产生链上交易，也不会生成 TXID。", "This guide creates no on-chain transaction or TXID."), sources: [sources.metamaskInstall, sources.ledgerPhrase, sources.ledgerBuy, sources.ftcScams],
  }),
  tutorial({
    id: "P0-02", slug: "coin-chain-network-address-gas", title: l("币、链、网络、地址、Gas 是什么", "Asset, chain, network, address, and gas"), summary: l("用一条转账路径理解五个最容易混淆的概念。", "Understand five commonly confused concepts through one transfer path."), goal: l("在提交转账前能独立核对资产、网络、地址和费用。", "Independently verify asset, network, address, and fees before sending."), task: "basics", platforms: ["通用 / General"], devices: ["网页 / Web", "手机 / Mobile"], regions: ["全球 / Global"], coins: ["USDT", "ETH", "BTC"], networks: ["Ethereum", "Tron", "BNB Smart Chain", "Bitcoin"], risk: "high", duration: l("10–15 分钟", "10–15 min"), feeType: l("学习无费用；转账需网络费", "No learning fee; transfers require network fees"), scope: l("适用于任何链上充币、提币或钱包间转账前。", "For any on-chain deposit, withdrawal, or wallet transfer."), prerequisites: [l("准备一组演示地址，不使用真实大额账户", "Use a demo address, not a real high-value account"), l("知道自己要发送的币种", "Know which asset you intend to send")],
    steps: [step("1", "币不是网络", "An asset is not a network", "USDT 等同名资产可存在于多条网络。选择币种后仍必须选择接收端支持的同一网络。", "The same asset, such as USDT, can exist on multiple networks. After choosing the asset, select the exact network supported by the receiver.", ["okx-withdraw"]), step("2", "地址属于特定网络", "An address belongs to a network", "地址格式相似不代表网络兼容。只能从接收端该币种、该网络的页面复制地址。", "Similar-looking addresses do not imply compatibility. Copy the address from the receiver's page for that exact asset and network.", ["okx-deposit"], img("okx-deposit.webp", "欧易官方充币地址说明", "OKX official deposit address guide", "okx-deposit")), step("3", "Gas 是网络执行费", "Gas is the network execution fee", "钱包转账通常需要该网络的原生币支付 Gas，例如 Ethereum 网络常用 ETH。平台提币费可能直接从提现金额扣除。", "Wallet transfers usually need the network's native asset for gas, such as ETH on Ethereum. Exchange withdrawal fees may be deducted from the amount.", ["metamask-send"]), step("4", "把五项连成一条路径", "Connect all five fields", "发送 USDT → 选择 Ethereum → 粘贴 Ethereum 接收地址 → 准备 ETH Gas → 核对净到账金额。任何一项不一致都先停止。", "Send USDT → choose Ethereum → paste the Ethereum receiving address → hold ETH for gas → verify the net amount. Stop if any field differs.", ["metamask-send", "okx-withdraw"] )], checklist: transferChecklist, success: [l("能说出同一币种可能存在多条网络", "You understand one asset may exist on multiple networks"), l("能在接收端找到网络、地址和 Memo/Tag 要求", "You can find the receiver's network, address, and Memo/Tag requirements")], txid: l("TXID 是某条链上的交易标识，只能在对应网络的区块浏览器查询。", "A TXID identifies a transaction on one chain and must be checked in that network's explorer."), sources: [sources.okxWithdraw, sources.okxDeposit, sources.metamaskSend],
  }),
  tutorial({
    id: "P0-03", slug: "download-official-software-wallet", title: l("如何识别官网并安全下载软件钱包", "How to verify and download an official software wallet"), summary: l("避开搜索广告、仿冒 App 和假扩展。", "Avoid search ads, fake apps, and counterfeit extensions."), goal: l("从可复核的官方入口安装正确的钱包，并完成安装后核对。", "Install the correct wallet from a verifiable official source and check it afterward."), task: "software-wallet", platforms: ["MetaMask", "TokenPocket", "Pi Wallet"], devices: ["手机 / Mobile", "浏览器扩展 / Extension"], regions: ["全球 / Global"], coins: ["通用 / Any"], networks: ["通用 / Any"], risk: "high", duration: l("10–20 分钟", "10–20 min"), feeType: l("官方软件下载通常免费", "Official wallet software is normally free"), scope: l("适用于首次安装或更换设备；不含导入真实助记词演示。", "For first install or a new device; does not demonstrate importing a real recovery phrase."), prerequisites: [l("准备更新过的系统与浏览器", "Use an updated operating system and browser"), l("关闭远程协助与屏幕共享", "Turn off remote assistance and screen sharing")],
    steps: [step("1", "从已核验入口进入", "Open a verified entry", "直接输入已知官网或使用本站钱包官方入口，不点击搜索结果中的广告下载按钮。核对拼写、HTTPS 与展示域名。", "Type a known official domain or use this site's official wallet entry. Avoid sponsored download results; verify spelling, HTTPS, and the displayed domain.", ["metamask-real"], img("metamask-real.webp", "MetaMask 官方防仿冒说明", "MetaMask official anti-counterfeit guidance", "metamask-real")), step("2", "让官网跳转到应用商店", "Let the site route you to the store", "移动端从官网进入官方商店页面；扩展从官网进入浏览器商店。核对开发者名称、下载量只是辅助，不是唯一依据。", "On mobile or extension stores, follow the link from the official website. Verify the publisher; download count is supporting evidence, not proof.", ["metamask-install"]), step("3", "安装后再次核对", "Recheck after installation", "确认图标、开发者、权限请求和首次打开页面与官方说明一致。若一打开就要求输入助记词以‘验证账户’，立即卸载并报告。", "Verify the icon, publisher, permissions, and first-run screen. If it immediately requests a recovery phrase to 'verify' an account, uninstall and report it.", ["metamask-install", "metamask-real"]), step("4", "保存官方入口", "Bookmark the official entry", "将官网加入书签。后续更新或恢复时从书签进入，不使用群聊安装包、网盘或客服发来的链接。", "Bookmark the official site. For updates or recovery, use that bookmark—not chat files, cloud-drive packages, or support links.", ["metamask-real"])], checklist: [l("域名与本站展示的官方域名一致", "Domain matches the official domain shown here"), l("下载页由官网跳转进入", "Download page was reached from the official site"), l("开发者与权限请求无异常", "Publisher and permissions look expected"), l("未向任何页面提供助记词或私钥", "No recovery phrase or private key was provided")], success: [l("钱包来自官方入口并可正常打开", "Wallet opens and came from the official entry"), l("已保存官网书签和离线备份计划", "Official site is bookmarked and an offline backup plan exists")], txid: l("安装钱包不会产生 TXID。首次收币后才会出现链上记录。", "Installing a wallet creates no TXID; one appears only after an on-chain transaction."), sources: [sources.metamaskInstall, sources.metamaskReal],
  }),
  tutorial({
    id: "P0-04", slug: "protect-recovery-phrase-private-key-password", title: l("助记词、私钥、密码如何安全保管", "Protect recovery phrases, private keys, and passwords"), summary: l("分清三种凭证的作用与丢失后果。", "Understand three credentials and what happens if each is lost."), goal: l("建立离线、可恢复、不会被单点泄露的备份。", "Create an offline, recoverable backup without a single digital leak point."), task: "security", platforms: ["通用 / General", "Ledger"], devices: ["手机 / Mobile", "电脑 / Desktop", "硬件 / Hardware"], regions: ["全球 / Global"], coins: ["通用 / Any"], networks: ["通用 / Any"], risk: "high", duration: l("15–30 分钟", "15–30 min"), feeType: l("纸质备份无平台费用", "Paper backup has no platform fee"), scope: l("适合创建或审查自托管钱包备份。", "For creating or reviewing a self-custody wallet backup."), prerequisites: [l("选择无摄像头、无旁观者的私密环境", "Choose a private space without cameras or observers"), l("准备耐久的离线书写介质", "Prepare durable offline writing material")],
    steps: [step("1", "理解恢复短语", "Understand the recovery phrase", "恢复短语可重建钱包控制权，掌握它的人通常无需密码即可转走资产。它不是普通验证码。", "A recovery phrase can recreate wallet control; anyone holding it can usually move assets without your app password. It is not a verification code.", ["ledger-phrase"], img("ledger-phrase.webp", "Ledger 官方恢复短语说明", "Ledger official recovery phrase explanation", "ledger-phrase")), step("2", "只做离线备份", "Create offline-only backups", "按钱包显示顺序手写并复核，不截图、不复制到云盘、邮箱、笔记 App、打印店或聊天工具。", "Write it by hand in the shown order and verify it. Do not screenshot or copy it to cloud storage, email, notes, a print shop, or chat.", ["ledger-phrase"]), step("3", "分开存放与演练", "Separate storage and rehearse", "将备份与设备分开保管，避免同一火灾、盗窃或误丢同时破坏两者。使用空钱包或厂商官方流程做恢复演练。", "Store backup and device separately so one fire, theft, or loss cannot destroy both. Rehearse recovery with an empty wallet or the vendor's official process.", ["ledger-phrase"]), step("4", "区分 App 密码", "Distinguish the app password", "本地密码通常只锁定当前设备上的钱包界面，忘记后可能用助记词恢复；它不能替代助记词备份。", "A local password usually locks the wallet interface on one device. Recovery may use the phrase, so the password is not a substitute for that backup.", ["metamask-install"])], checklist: [l("没有任何数字版助记词照片或云端副本", "No digital photo or cloud copy exists"), l("备份顺序已人工复核", "Word order was manually verified"), l("设备与备份不在同一处", "Device and backup are stored separately"), l("可信家属或继承安排不暴露完整凭证", "Inheritance planning does not expose the full credential")], success: [l("能解释助记词、私钥和本地密码的区别", "You can explain phrase, private key, and local password"), l("已有至少一份可读、离线且安全存放的备份", "At least one readable offline backup is stored safely")], txid: l("备份操作不产生 TXID，也不应要求链上转账。", "Backup creates no TXID and should require no transaction."), sources: [sources.ledgerPhrase, sources.metamaskInstall],
  }),
  tutorial({
    id: "P0-05", slug: "exchange-account-security", title: l("交易所账户基础安全设置", "Exchange account security basics"), summary: l("用独立密码、2FA 与提现保护降低账户风险。", "Reduce account risk with unique credentials, 2FA, and withdrawal controls."), goal: l("完成登录与提现两层防护，并建立异常时的停用路径。", "Protect both login and withdrawals and know how to react to anomalies."), task: "exchange-security", platforms: ["火币 / HTX", "欧易 / OKX", "币安 / Binance"], devices: ["手机 / Mobile", "网页 / Web"], regions: ["全球 / Global"], coins: ["通用 / Any"], networks: ["通用 / Any"], risk: "high", duration: l("15–25 分钟", "15–25 min"), feeType: l("通常无费用", "Normally none"), scope: l("适用于已注册的交易所账户；具体选项随地区和账户等级变化。", "For existing exchange accounts; options vary by region and account tier."), prerequisites: [l("从本站入口或已保存书签登录", "Log in from this directory or a saved bookmark"), l("准备密码管理器和独立验证器", "Prepare a password manager and separate authenticator")],
    steps: [step("1", "设置唯一密码", "Use a unique password", "使用密码管理器生成与其他网站不重复的长密码。不要把登录密码和资金密码设为相同。", "Generate a long unique password with a password manager. Do not reuse it as a fund password.", ["ftc-scams"]), step("2", "启用独立 2FA", "Enable independent 2FA", "优先使用验证器或安全密钥，并离线保存恢复码。短信可作为补充，但要考虑换卡攻击风险。", "Prefer an authenticator or security key and store recovery codes offline. SMS can supplement this but is exposed to SIM-swap risk.", ["ftc-scams"]), step("3", "开启提现保护", "Enable withdrawal protection", "如平台提供，开启反钓鱼码、新设备提醒、提现白名单和新增地址冷却期。先确认紧急冻结入口。", "Where available, enable anti-phishing codes, new-device alerts, address allowlists, and cooling periods. Locate emergency freeze controls first.", ["okx-withdraw"]), step("4", "进行无资金演练", "Run a no-funds rehearsal", "退出后从书签重新登录，确认 2FA、反钓鱼码和通知正常。不要为了测试而进行真实提币。", "Sign out and log in again from the bookmark to confirm 2FA, anti-phishing codes, and alerts. No real withdrawal is needed.", ["okx-withdraw"])], checklist: [l("密码只用于该平台", "Password is unique to this platform"), l("2FA 恢复码已离线保存", "2FA recovery codes are stored offline"), l("登录和提现通知已开启", "Login and withdrawal alerts are enabled"), l("知道如何冻结账户与联系官方客服", "You know how to freeze the account and reach official support")], success: [l("新设备登录需要第二因素", "A new-device login requires a second factor"), l("提现前会触发额外核对或白名单规则", "Withdrawals trigger extra checks or allowlist rules")], txid: l("安全设置不产生 TXID。不要通过真实转账来测试登录保护。", "Security settings create no TXID; do not test them with a real transfer."), sources: [sources.okxWithdraw, sources.ftcScams],
  }),
  tutorial({
    id: "P0-06", slug: "fiat-on-ramp-decision-guide", title: l("法币入金通用决策指南", "Global fiat on-ramp decision guide"), summary: l("先判断地区、KYC、支付方与费用，再选择当地可用路径。", "Check region, KYC, payment provider, and fees before choosing a local route."), goal: l("建立合规的入金判断流程，不依赖绕过限制的渠道。", "Build a compliant on-ramp decision process without bypassing restrictions."), task: "fiat-in", platforms: ["通用 / General"], devices: ["网页 / Web", "手机 / Mobile"], regions: ["按当地规则 / Local rules"], coins: ["法币 / Fiat", "稳定币 / Stablecoin"], networks: ["平台内部 / Off-chain"], risk: "high", duration: l("15–30 分钟 + 到账等待", "15–30 min + settlement"), feeType: l("支付费、点差、第三方服务费", "Payment fee, spread, third-party fee"), scope: l("全球通用判断框架；不推荐具体银行、卡、P2P 对手或规避方案。", "A global decision framework; no specific bank, card, P2P counterparty, or bypass method is recommended."), prerequisites: [l("确认居住地、国籍与平台地区版本", "Confirm residence, nationality, and platform region"), l("阅读当地法律、税务和平台资格要求", "Review local law, tax, and platform eligibility")],
    steps: [step("1", "确认地区与资格", "Confirm region and eligibility", "在平台官方支持页面核对服务是否向你所在地区开放、是否需要 KYC、年龄和账户类型要求。不可用就停止，不切换虚假地区。", "Check official support for regional availability, KYC, age, and account type. If unavailable, stop; do not misrepresent your region.", ["ftc-scams"]), step("2", "识别收款与支付主体", "Identify payment parties", "确认资金支付给平台、银行还是第三方服务商；核对名称、退款政策、到账时间和客服责任边界。", "Identify whether payment goes to the platform, bank, or third-party provider; verify names, refund policy, settlement time, and support responsibility.", ["ftc-scams"]), step("3", "比较总成本", "Compare total cost", "同时比较支付手续费、汇率点差、链上提币费和最小金额，不只看页面上最醒目的费率。", "Compare payment fees, FX spread, later withdrawal fees, and minimums—not only the headline rate.", ["okx-withdraw"]), step("4", "先用可承受的小额", "Start with a manageable amount", "首次使用新渠道时，先完成可承受的小额流程并保存订单记录。到账后确认资产是否可用、是否有冻结期。", "For a new route, complete a manageable small transaction and retain the order record. After settlement, check availability and holding periods.", ["coinbase-memo"])], checklist: [l("地区与平台版本匹配", "Region matches platform version"), l("已了解 KYC 与第三方支付方", "KYC and third-party provider are understood"), l("已比较费用、点差、限额与到账时间", "Fees, spread, limits, and settlement time were compared"), l("使用本人同名且当地允许的支付方式", "Payment method is allowed locally and in your own name"), l("未接受私聊换币、代付或绕过限制建议", "No private swap, proxy payment, or bypass offer is involved")], success: [l("订单状态显示完成且资产进入可用或明确的冻结状态", "Order is complete and assets are available or in a clearly stated hold"), l("保存了订单号、支付凭证与官方客服入口", "Order ID, payment evidence, and official support entry are saved")], txid: l("法币购买可能先只有订单号；只有平台发起链上交付时才会有 TXID。", "A fiat purchase may initially have only an order ID; a TXID appears only if on-chain delivery occurs."), sources: [sources.ftcScams, sources.okxWithdraw, sources.coinbaseMemo],
  }),
  tutorial({
    id: "P0-07", slug: "find-exchange-deposit-address", title: l("如何找到交易所充币地址", "How to find an exchange deposit address"), summary: l("从钱包充到交易所前，正确获取网络、地址与 Memo/Tag。", "Get the right network, address, and Memo/Tag before depositing to an exchange."), goal: l("生成并核对一组可用的交易所充币信息。", "Generate and verify a valid exchange deposit destination."), task: "deposit-exchange", platforms: ["欧易 / OKX", "通用 / General"], devices: ["网页 / Web", "手机 / Mobile"], regions: ["全球 / Global"], coins: ["USDT", "XRP", "XLM", "ATOM"], networks: ["Ethereum", "Tron", "XRP Ledger", "Stellar"], risk: "high", duration: l("8–15 分钟", "8–15 min"), feeType: l("接收通常免费；发送端收网络费", "Receiving is usually free; sender pays network fee"), scope: l("适用于从自托管钱包向交易所链上充币。", "For on-chain deposits from a self-custody wallet to an exchange."), prerequisites: [l("交易所账户已通过所需验证并可充币", "Exchange account is verified as required and deposits are available"), l("发送钱包有资产及对应网络 Gas", "Sending wallet has the asset and required gas")],
    steps: [step("1", "进入充币而非法币充值", "Open crypto deposit, not fiat deposit", "从资产页面选择‘充币/Deposit crypto’，不要进入银行卡购币或内部转账。选择要接收的币种。", "From assets, choose Deposit crypto—not card purchase or internal transfer—then select the asset.", ["okx-deposit"], img("okx-deposit.webp", "欧易官方充币地址与标签说明", "OKX official deposit address and tag guide", "okx-deposit")), step("2", "选择发送端可用的同一网络", "Choose the exact sending network", "接收页网络必须与发送钱包当前资产所在网络一致。不要因为手续费低而选择另一条同名网络。", "The receiving network must match where the asset exists in the sending wallet. Do not switch to a cheaper same-name network.", ["okx-deposit"]), step("3", "复制地址与 Memo/Tag", "Copy address and Memo/Tag", "若页面同时显示地址和 Memo/Tag，两项都要复制。记录最低充币金额、确认数和暂停状态。", "If both address and Memo/Tag appear, copy both. Note minimum deposit, confirmation count, and any suspension notice.", ["okx-deposit", "coinbase-memo"]), step("4", "小额测试并等待确认", "Send a small test and wait", "先从钱包发送可承受的小额，保存 TXID。交易所显示到账后，再使用同一组核验信息发送剩余金额。", "Send a manageable test amount and save the TXID. After crediting, reuse the verified fields for the remainder.", ["coinbase-memo"])], checklist: transferChecklist, success: [l("交易所记录显示正确币种、网络和到账数量", "Exchange record shows the correct asset, network, and credited amount"), l("可在对应链浏览器查询测试交易 TXID", "The test TXID is visible in the correct explorer")], txid: l("发送钱包的活动记录会显示 TXID。用交易所指定网络的区块浏览器查询确认数。", "The sending wallet shows the TXID; check confirmations in the explorer for the network chosen by the exchange."), sources: [sources.okxDeposit, sources.coinbaseMemo],
  }),
  tutorial({
    id: "P0-08", slug: "withdraw-exchange-to-wallet", title: l("交易所提币到钱包", "Withdraw from an exchange to a wallet"), summary: l("从托管账户安全转入自托管钱包。", "Move assets from a custodial account to a self-custody wallet."), goal: l("完成一次网络匹配、地址核对和小额测试的链上提币。", "Complete an on-chain withdrawal with network matching, address checks, and a small test."), task: "withdraw-wallet", platforms: ["欧易 / OKX", "币安 / Binance", "MetaMask"], devices: ["网页 / Web", "手机 / Mobile"], regions: ["全球 / Global"], coins: ["USDT", "ETH", "BTC"], networks: ["Ethereum", "Tron", "BNB Smart Chain", "Bitcoin"], risk: "high", duration: l("10–30 分钟", "10–30 min"), feeType: l("平台提币费与可能的网络费", "Platform withdrawal and possible network fees"), scope: l("适用于交易所支持的正常链上提币；不含跨链桥。", "For supported on-chain exchange withdrawals; excludes bridges."), prerequisites: [l("钱包已从官方入口安装并完成离线备份", "Wallet is official and backed up offline"), l("交易所账户可提币且无冷却限制", "Exchange withdrawals are available with no active hold")],
    steps: [step("1", "在钱包生成接收信息", "Generate receiving details in the wallet", "在钱包选定币种和网络后复制地址。确认钱包确实支持该网络，不手动猜测。", "Choose the asset and network in the wallet, then copy the address. Confirm support; do not infer it from the format.", ["metamask-receive"]), step("2", "选择链上提币", "Choose on-chain withdrawal", "在交易所选择提币到链上地址，粘贴地址并选择与钱包完全一致的网络。若接收方要求 Memo/Tag，必须填写。", "Choose withdrawal to an on-chain address, paste it, and select the exact same wallet network. Include Memo/Tag if required.", ["okx-withdraw"], img("okx-withdraw.webp", "欧易官方网页端提币说明", "OKX official web withdrawal guide", "okx-withdraw")), step("3", "核对净到账与安全验证", "Verify net amount and security", "查看手续费、最小提币额和预计到账量。完成平台 2FA，但不向任何人转发验证码。", "Review fee, minimum, and net amount. Complete platform 2FA, but never forward a code to anyone.", ["okx-withdraw"]), step("4", "先小额测试", "Test with a small amount", "首次地址先提可承受的小额。保存订单号和 TXID，钱包确认到账后再提剩余金额。", "For a new address, withdraw a manageable test amount. Save order ID and TXID, then continue only after wallet receipt.", ["coinbase-memo", "metamask-receive"])], checklist: transferChecklist, success: [l("平台状态为已发送/完成且给出 TXID", "Platform status is sent/completed and provides a TXID"), l("钱包在同一网络显示正确资产和数量", "Wallet shows the correct asset and amount on the same network")], txid: l("平台生成 TXID 后，复制到对应网络区块浏览器。平台‘审核中’阶段可能尚无 TXID。", "Once the platform creates a TXID, open it in the matching explorer. A review-pending withdrawal may not have one yet."), sources: [sources.okxWithdraw, sources.metamaskReceive, sources.coinbaseMemo],
  }),
  tutorial({
    id: "P0-09", slug: "wallet-receive-and-send", title: l("钱包收币与转币", "Receive and send with a wallet"), summary: l("完成钱包间基础转账，并正确准备 Gas。", "Complete a wallet-to-wallet transfer and prepare the right gas."), goal: l("在钱包内完成接收地址核对、发送和链上确认。", "Verify a receiving address, send, and confirm on-chain."), task: "wallet-transfer", platforms: ["MetaMask", "通用 / General"], devices: ["手机 / Mobile", "浏览器扩展 / Extension"], regions: ["全球 / Global"], coins: ["ETH", "USDT"], networks: ["Ethereum", "EVM"], risk: "high", duration: l("8–20 分钟", "8–20 min"), feeType: l("网络 Gas", "Network gas"), scope: l("适用于同一网络的钱包间转账；不含跨链。", "For wallet transfers on the same network; excludes bridging."), prerequisites: [l("两端钱包均来自官方入口", "Both wallets are from official entries"), l("发送端有对应网络原生 Gas 币", "Sender holds the network's native gas asset")],
    steps: [step("1", "接收端选择网络并复制地址", "Choose network and copy receiving address", "在接收钱包顶部确认网络，再打开收款并复制地址。通过第二渠道核对首尾字符。", "Confirm the network in the receiving wallet, open Receive, and copy the address. Verify first and last characters through a second channel.", ["metamask-send"]), step("2", "发送端选择同一网络", "Select the same sending network", "在发送钱包切换到相同网络，选择资产并点击发送。粘贴地址后再次核对，不使用地址历史里的相似地址。", "Switch the sender to the same network, select the asset, and send. Recheck after pasting; avoid lookalike entries in address history.", ["metamask-send"], img("metamask-send.webp", "MetaMask 官方发送代币说明", "MetaMask official token sending guide", "metamask-send")), step("3", "设置金额并查看 Gas", "Set amount and review gas", "保留足够原生币支付本次和后续必要操作。手续费异常高时先暂停，检查网络拥堵和代币合约。", "Keep enough native asset for this and necessary later actions. If fees look abnormal, pause and verify congestion and token contract.", ["metamask-send"]), step("4", "提交小额并查 TXID", "Send a test and check TXID", "先发小额，提交后从活动记录打开 TXID。等待接收钱包显示正确余额和确认数，再进行剩余转账。", "Send a test first, then open its TXID from Activity. Wait for the receiving wallet and confirmations before sending more.", ["metamask-send"])], checklist: transferChecklist, success: [l("发送端状态成功且可查看 TXID", "Sender shows success and a TXID"), l("接收端在正确网络显示资产", "Receiver shows the asset on the correct network")], txid: l("TXID 可证明交易已广播或确认，但不代表接收 App 一定立即显示代币；仍需核对网络和代币合约。", "A TXID proves broadcast or confirmation, but the receiving app may not immediately display the token; verify network and token contract."), sources: [sources.metamaskSend],
  }),
  tutorial({
    id: "P0-10", slug: "funds-not-arrived-txid", title: l("为什么币没到账：从 TXID 开始排查", "Funds missing? Start with the TXID"), summary: l("先区分平台处理中、链上未确认和钱包未显示。", "Separate platform processing, chain confirmation, and wallet display issues."), goal: l("不再次转账的情况下定位不到账所处环节。", "Locate the failure stage without sending again."), task: "troubleshoot", platforms: ["通用 / General", "MetaMask"], devices: ["网页 / Web", "手机 / Mobile"], regions: ["全球 / Global"], coins: ["通用 / Any"], networks: ["Ethereum", "Tron", "Bitcoin", "EVM"], risk: "high", duration: l("10–40 分钟", "10–40 min"), feeType: l("查询免费；不要支付‘解冻费’", "Lookup is free; never pay an 'unlock fee'"), scope: l("适用于已提交的链上交易；平台内部转账需查订单号。", "For submitted on-chain transfers; internal transfers use order IDs instead."), prerequisites: [l("准备发送平台订单号或钱包活动记录", "Have the platform order ID or wallet activity record"), l("不要再次发送同样金额", "Do not send the same amount again")],
    steps: [step("1", "先确认是否已有 TXID", "Check whether a TXID exists", "平台若仍显示审核中或处理中，链上可能尚无交易。只有出现 TXID 后，才进入区块浏览器排查。", "If the platform is reviewing or processing, no on-chain transaction may exist. Use an explorer only after a TXID appears.", ["okx-withdraw"]), step("2", "在正确网络查询", "Search on the correct network", "根据发送记录选择对应网络区块浏览器，粘贴 TXID。不要把地址当成 TXID，也不要点击陌生人发来的浏览器链接。", "Use the explorer for the sending network and paste the TXID. Do not confuse an address with a TXID or open a stranger's explorer link.", ["metamask-receive"]), step("3", "读取交易状态", "Read transaction status", "Pending 表示等待确认；Failed 表示链上失败；Success 表示资产已到目标地址。核对 To、资产合约和数量。", "Pending awaits confirmation, Failed means on-chain failure, and Success means delivery to the target address. Verify To, token contract, and amount.", ["metamask-receive"], img("metamask-receive.webp", "MetaMask 官方收款排查说明", "MetaMask official receiving troubleshooting guide", "metamask-receive")), step("4", "按结果处理", "Act on the result", "成功但钱包不显示：切换正确网络并从官方来源核对代币合约；成功但交易所未入账：提交 TXID、币种、网络、金额和 Memo/Tag 给官方客服。", "Success but hidden in wallet: switch to the right network and verify the token contract from an official source. Success but exchange not credited: provide TXID, asset, network, amount, and Memo/Tag to official support.", ["okx-deposit", "metamask-receive"])], checklist: [l("订单状态与 TXID 是否存在", "Order status and whether a TXID exists"), l("区块浏览器网络与发送网络一致", "Explorer matches the sending network"), l("To 地址、代币合约和数量正确", "To address, token contract, and amount are correct"), l("交易所所需 Memo/Tag 已填写", "Required exchange Memo/Tag was included"), l("没有向‘客服’支付额外解冻费", "No extra 'unlock fee' was paid to support")], success: [l("已定位到平台、链上或显示层中的一个环节", "The issue is located at platform, chain, or display layer"), l("已保存可提交给官方客服的完整非敏感证据", "Complete non-sensitive evidence is ready for official support")], txid: l("TXID、发送/接收地址和链上金额通常是公开信息；助记词、私钥、验证码永远不是排查材料。", "TXID, addresses, and on-chain amounts are generally public. Recovery phrases, private keys, and codes are never troubleshooting evidence."), sources: [sources.okxWithdraw, sources.okxDeposit, sources.metamaskReceive],
  }),
  tutorial({
    id: "P0-11", slug: "fiat-off-ramp-decision-guide", title: l("法币出金通用决策指南", "Global fiat off-ramp decision guide"), summary: l("按地区规则判断卖出、结算与银行到账路径。", "Evaluate sale, settlement, and bank payout under local rules."), goal: l("建立合规出金流程，并提前识别冻结期、同名账户和税务记录要求。", "Build a compliant off-ramp flow and identify holds, same-name rules, and recordkeeping needs."), task: "fiat-out", platforms: ["通用 / General"], devices: ["网页 / Web", "手机 / Mobile"], regions: ["按当地规则 / Local rules"], coins: ["法币 / Fiat", "稳定币 / Stablecoin"], networks: ["平台内部 / Off-chain"], risk: "high", duration: l("20–60 分钟 + 银行处理", "20–60 min + bank processing"), feeType: l("交易费、点差、提现费、银行费", "Trading, spread, withdrawal, and bank fees"), scope: l("全球通用判断框架；不提供代收代付、拆单或规避银行风控方案。", "A global framework; no proxy payment, transaction splitting, or bank-control bypass advice."), prerequisites: [l("确认平台在当地允许法币提现", "Confirm fiat withdrawal is available locally"), l("准备本人同名银行或支付账户", "Prepare an account in your own legal name")],
    steps: [step("1", "确认资产可用状态", "Confirm available balance", "区分总余额、可交易余额与可提现余额。法币购入、充值或安全设置变更后可能有冻结期。", "Distinguish total, tradable, and withdrawable balances. Purchases, deposits, or security changes may trigger holds.", ["okx-withdraw"]), step("2", "核对地区与收款主体", "Verify region and recipient", "确认当地支持的法币、提现方式、账户同名要求和第三方支付方。不可用时停止，不借用他人账户。", "Confirm supported fiat, payout methods, same-name rules, and third-party providers. Stop if unavailable; do not borrow another person's account.", ["ftc-scams"]), step("3", "试算净到账", "Estimate net proceeds", "比较卖出点差、交易费、提现费、银行中转费、最低限额和预计时间，并保留税务所需成本记录。", "Compare sale spread, trading fee, withdrawal fee, bank intermediary fee, minimum, and timing. Preserve cost-basis records for tax needs.", ["ftc-scams"]), step("4", "小额完成闭环", "Complete a small end-to-end test", "先提取可承受的小额到本人同名账户，保存订单与银行入账记录。确认路径正常后再决定后续金额。", "Withdraw a manageable test to your own same-name account and keep platform and bank records. Continue only after the path works.", ["coinbase-memo"])], checklist: [l("地区、法币和平台版本支持提现", "Region, fiat, and platform version support withdrawal"), l("收款账户与认证姓名一致", "Recipient account matches the verified name"), l("可提现余额与冻结期已确认", "Withdrawable balance and holds are confirmed"), l("费用、点差、到账时间与税务记录已核对", "Fees, spread, timing, and tax records are checked"), l("未使用代收、私聊换币或规避风控方式", "No proxy receipt, private swap, or control bypass is used")], success: [l("平台订单完成且本人账户收到对应法币", "Platform order completes and your own account receives fiat"), l("订单、成交、费用与银行记录已保存", "Order, trade, fee, and bank records are stored")], txid: l("平台内部卖出和银行提现通常使用订单号，不一定有链上 TXID。", "Internal sale and bank payout usually use order IDs, not an on-chain TXID."), sources: [sources.okxWithdraw, sources.ftcScams, sources.coinbaseMemo],
  }),
  tutorial({
    id: "P0-12", slug: "buy-download-verify-hardware-wallet", title: l("硬件钱包购买、客户端下载与设备验真", "Buy, install, and authenticate a hardware wallet"), summary: l("从正规来源获得设备，校验客户端并拒绝预置助记词。", "Source a genuine device, verify its app, and reject pre-seeded phrases."), goal: l("完成从购买到首次验真的供应链安全检查。", "Complete supply-chain checks from purchase through first authentication."), task: "hardware-wallet", platforms: ["Ledger", "Trezor"], devices: ["硬件 / Hardware", "电脑 / Desktop"], regions: ["官方可配送地区 / Supported shipping regions"], coins: ["通用 / Any"], networks: ["通用 / Any"], risk: "high", duration: l("购买等待 + 20–40 分钟", "Shipping + 20–40 min"), feeType: l("设备、配送与可能的税费", "Device, shipping, and possible taxes"), scope: l("适用于新设备；不建议购买来源不明或预先初始化的二手设备。", "For new devices; unknown-source or pre-initialized used devices are not recommended."), prerequisites: [l("确认厂商官网与当地配送政策", "Confirm vendor website and local shipping policy"), l("准备一台已更新且无远程控制软件的电脑", "Use an updated computer without remote-control software")],
    steps: [step("1", "从官方或授权渠道购买", "Buy from an official or authorized source", "从厂商官网进入购买渠道，核对销售主体、包装说明和退换政策。价格异常低或附带已写好的助记词应立即拒收。", "Use the vendor site to reach an official or authorized seller. Check merchant, packaging, and returns. Reject unusually cheap or pre-seeded devices.", ["ledger-buy"], img("ledger-buy.webp", "Ledger 官方安全购买说明", "Ledger official secure-purchase guidance", "ledger-buy")), step("2", "检查包装但不迷信封条", "Inspect packaging, not just seals", "记录开箱状态、设备型号和配件。封条可能被仿造，最终仍需通过官方客户端和设备自检完成真实性验证。", "Record package condition, model, and accessories. Seals can be copied; rely on official software and device authentication too.", ["ledger-buy", "trezor-auth"]), step("3", "下载并验证官方客户端", "Download and verify official software", "只从厂商官网进入客户端下载页。若官方提供签名或哈希校验，按当前系统说明完成验证。", "Download only through the vendor site. If signatures or hashes are provided, follow the current OS-specific verification guide.", ["trezor-suite"], img("trezor-suite.webp", "Trezor Suite 官方下载校验页面", "Official Trezor Suite download verification page", "trezor-suite")), step("4", "运行设备真实性检查", "Run device authentication", "连接后由官方客户端执行真实性检查，并确认设备要求你在本机生成新助记词。任何预置助记词、客服要求共享屏幕都应停止。", "Use the official app's authenticity check and ensure the device generates a new phrase locally. Stop for any pre-seeded phrase or support screen-share request.", ["trezor-auth"], img("trezor-auth.webp", "Trezor 设备真实性检查说明", "Trezor device authentication guidance", "trezor-auth"))], checklist: [l("购买渠道可从厂商官网追溯", "Seller is traceable from the vendor site"), l("包装、型号和配件与订单一致", "Package, model, and accessories match the order"), l("客户端从官网获取并完成可用的校验", "Software came from the official site and available verification was completed"), l("设备通过官方真实性检查", "Device passed official authentication"), l("设备未附带或预置助记词", "No recovery phrase was included or pre-installed")], success: [l("官方客户端识别设备为真且固件状态正常", "Official software recognizes a genuine device with valid firmware"), l("新助记词仅在设备或官方初始化流程中生成", "A new phrase was generated only by the device or official setup")], txid: l("购买、安装和验真不会产生 TXID。此阶段不要向设备地址转账。", "Buying, installing, and authenticating creates no TXID. Do not fund it yet."), sources: [sources.ledgerBuy, sources.trezorSuite, sources.trezorAuth],
  }),
  tutorial({
    id: "P0-13", slug: "hardware-wallet-backup-receive-test", title: l("硬件钱包备份、收款与小额测试", "Hardware wallet backup, receive, and test"), summary: l("在设备屏幕核对地址，完成第一次安全入库。", "Verify the address on-device and complete a first safe deposit."), goal: l("建立可恢复备份并完成小额收款与验证。", "Create a recoverable backup and complete a verified small deposit."), task: "hardware-wallet", platforms: ["Ledger", "Trezor", "通用 / General"], devices: ["硬件 / Hardware", "电脑 / Desktop"], regions: ["全球 / Global"], coins: ["BTC", "ETH"], networks: ["Bitcoin", "Ethereum"], risk: "high", duration: l("25–45 分钟", "25–45 min"), feeType: l("发送端提币费或网络 Gas", "Sender withdrawal fee or network gas"), scope: l("适用于已通过真实性检查的新硬件钱包。", "For a new hardware wallet that has passed authentication."), prerequisites: [l("已完成 P0-12 设备验真", "P0-12 device authentication is complete"), l("准备离线备份材料和小额测试资产", "Prepare offline backup material and a small test amount")],
    steps: [step("1", "离线记录恢复短语", "Record the phrase offline", "按设备显示顺序手写恢复短语并复核。不要拍照、打印、输入电脑或交给厂商客服。", "Write the phrase in device order and verify it. Do not photograph, print, type it into a computer, or give it to vendor support.", ["ledger-phrase"], img("ledger-phrase.webp", "Ledger 官方恢复短语说明", "Ledger official recovery phrase explanation", "ledger-phrase")), step("2", "在设备屏幕核对收款地址", "Verify receive address on the device", "在官方客户端生成收款地址，再在硬件设备屏幕逐段核对。电脑显示与设备不一致时立即断开并排查。", "Generate an address in official software, then compare it on the hardware display. Disconnect if computer and device differ.", ["trezor-auth"]), step("3", "发送小额测试", "Send a small test", "从交易所或已有钱包选择完全一致的网络，先发送可承受的小额。保存 TXID，等待足够确认。", "Use the exact same network from the sender, send a manageable test amount, save the TXID, and wait for confirmations.", ["coinbase-memo"]), step("4", "验证收款与恢复计划", "Verify receipt and recovery plan", "确认官方客户端余额与区块浏览器一致。将设备与备份分开存放，并安排使用空钱包或厂商官方流程的恢复演练。", "Confirm official software matches the explorer. Store device and backup separately and schedule an empty-wallet or vendor-guided recovery rehearsal.", ["ledger-phrase"])], checklist: transferChecklist, success: [l("设备屏幕与客户端显示的收款地址一致", "Device and app display the same receive address"), l("小额交易已确认且余额正确", "Test transaction is confirmed with the correct balance"), l("恢复短语离线、可读并与设备分开", "Phrase is offline, readable, and separate from the device")], txid: l("从发送端复制 TXID，在所选网络的官方或可信区块浏览器确认目标地址与数量。", "Copy the TXID from the sender and verify destination and amount in a trusted explorer for the chosen network."), sources: [sources.ledgerPhrase, sources.trezorAuth, sources.coinbaseMemo],
  }),
  tutorial({
    id: "P0-14", slug: "beginner-scam-checklist", title: l("新手防骗清单：钓鱼、假客服、授权与地址投毒", "Beginner scam checklist: phishing, fake support, approvals, and address poisoning"), summary: l("在点击、签名、转账和求助前识别常见诈骗信号。", "Spot common scam signals before clicking, signing, sending, or seeking help."), goal: l("建立一套遇到紧迫要求时也能执行的停止检查。", "Use a stop-check routine even under pressure."), task: "security", platforms: ["通用 / General"], devices: ["手机 / Mobile", "网页 / Web", "浏览器扩展 / Extension"], regions: ["全球 / Global"], coins: ["通用 / Any"], networks: ["通用 / Any"], risk: "high", duration: l("10–15 分钟", "10–15 min"), feeType: l("无；不要支付解冻或验证费", "None; never pay unlock or verification fees"), scope: l("适用于所有钱包、交易所、社交平台与远程客服场景。", "For wallets, exchanges, social platforms, and remote-support situations."), prerequisites: [l("暂停当前转账、签名或远程协助", "Pause the current transfer, signature, or remote session"), l("从独立设备或书签打开官方入口", "Open the official entry from a bookmark or separate device")],
    steps: [step("1", "识别紧迫与收益承诺", "Spot urgency and profit promises", "‘立即转账否则冻结’、‘保证收益’、‘先缴税/解冻费’都是高危信号。链上付款通常不可撤销。", "'Pay now or freeze,' guaranteed returns, and upfront tax/unlock fees are red flags. Crypto payments are generally irreversible.", ["ftc-scams"], img("ftc-scams.webp", "FTC 官方加密货币诈骗提示", "FTC official cryptocurrency scam guidance", "ftc-scams")), step("2", "拒绝假客服与远程控制", "Reject fake support and remote control", "官方客服不会索要助记词、私钥或让你安装远程控制软件转移资产。结束私聊后从官网重新进入客服。", "Official support will not request recovery phrases, private keys, or remote control to move funds. End private chats and reopen support from the official site.", ["ftc-scams", "ledger-phrase"]), step("3", "读懂签名与授权", "Read signatures and approvals", "看不懂的签名先拒绝。代币授权可能允许合约持续转走资产；核对域名、合约、额度和有效期，不因‘领取空投’放松。", "Reject signatures you do not understand. Token approvals may allow ongoing transfers; verify domain, contract, allowance, and duration.", ["ftc-scams"]), step("4", "防范地址投毒", "Defend against address poisoning", "不要从交易历史复制相似地址。每次从接收方当前页面重新复制，并核对首尾多位；大额前先小额测试。", "Do not copy lookalike addresses from history. Copy from the current recipient screen, compare several leading and trailing characters, and test first.", ["coinbase-memo"])], checklist: [l("没有人索要助记词、私钥或验证码", "No one is requesting a phrase, key, or code"), l("域名来自书签或已核验入口", "Domain came from a bookmark or verified entry"), l("看懂要签署的操作、合约和授权额度", "You understand the action, contract, and approval amount"), l("收款地址从当前接收页面复制并二次核对", "Address was copied from the current recipient screen and rechecked"), l("不存在紧迫、保证收益或额外解冻费", "No urgency, guaranteed return, or extra unlock fee exists")], success: [l("能在压力场景下主动停止并独立核验", "You can stop and independently verify under pressure"), l("可从官方入口报告假网站或假客服", "You can report a fake site or support account through official channels")], txid: l("已被骗时保留 TXID、地址、时间、聊天记录和网址，并尽快联系平台与当地执法机构；不要再付‘追回费’。", "If scammed, preserve TXID, addresses, time, messages, and URLs, then contact the platform and local authorities. Never pay a recovery fee."), sources: [sources.ftcScams, sources.ledgerPhrase, sources.coinbaseMemo],
  }),
];

export const tutorialBySlug = new Map(tutorials.map((item) => [item.slug, item]));

export const taskLabels: Record<string, LocalizedText> = {
  basics: l("基础认知", "Basics"),
  "software-wallet": l("软件钱包", "Software wallet"),
  security: l("安全设置", "Security"),
  "exchange-security": l("交易所安全", "Exchange security"),
  "fiat-in": l("我要入金", "Fiat on-ramp"),
  "deposit-exchange": l("我要充到交易所", "Deposit to exchange"),
  "withdraw-wallet": l("我要提到钱包", "Withdraw to wallet"),
  "wallet-transfer": l("钱包转账", "Wallet transfer"),
  troubleshoot: l("钱没到账", "Funds missing"),
  "fiat-out": l("我要出金", "Fiat off-ramp"),
  "hardware-wallet": l("设置硬件钱包", "Set up hardware wallet"),
};

export const riskLabels: Record<RiskLevel, LocalizedText> = {
  low: l("低风险", "Low risk"),
  medium: l("中风险", "Medium risk"),
  high: l("高风险", "High risk"),
};

export const highRiskReminders: LocalizedText[] = [
  l("任何客服都不应索要助记词或私钥。", "No support agent should ever ask for a recovery phrase or private key."),
  l("链上交易通常不可撤销。", "On-chain transactions are generally irreversible."),
  l("发送网络必须与接收网络一致。", "The sending network must match the receiving network."),
  l("需要 Memo/Tag 时，地址和 Memo/Tag 缺一不可。", "When Memo/Tag is required, both it and the address are mandatory."),
  l("首次或大额转账先小额测试。", "Test with a small amount before a first or large transfer."),
  l("从书签或已核验官方入口进入，不点击搜索广告中的下载链接。", "Use a bookmark or verified official entry; do not download through search ads."),
];
